import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { resolve, join } from "node:path";
import { describe, expect, it } from "vitest";
import { withTempDataDir } from "./helpers/temp-data-dir.js";
import { createTestServer, invokeJsonTool } from "./helpers/test-server.js";

/** Helper to extract text from MCP tool result */
function resultText(result: unknown): string {
  const r = result as { content: Array<{ type: string; text: string }> };
  return r.content
    .filter((c) => c.type === "text")
    .map((c) => c.text)
    .join("\n");
}

/** Minimal valid codebase analysis for tests */
const minimalAnalysis = {
  techStack: "TypeScript, Node.js",
  directoryStructure: "src/ for source, test/ for tests",
  fileNaming: "kebab-case.ts",
  codePatterns: "One function per file",
};

/** Full codebase analysis with optional fields */
const fullAnalysis = {
  ...minimalAnalysis,
  testingPatterns: "Vitest, co-located test files",
  additionalNotes: "Uses ESM modules exclusively",
};

describe("sync_agents_md", () => {
  it("writes AGENTS.md with full content to workspace path", async () => {
    await withTempDataDir(async (dataDir) => {
      const server = createTestServer();
      try {
        // Create a workspace directory inside the temp dir
        const wsDir = resolve(dataDir, "workspace");
        mkdirSync(wsDir, { recursive: true });

        await invokeJsonTool(server, "init_project", {
          name: "My Project",
          description: "A great project",
          workspacePaths: [wsDir],
        });

        // Populate overview with real content
        await invokeJsonTool(server, "update_project_doc", {
          slug: "my-project",
          doc: "overview",
          content:
            "# My Project\n\n> A great project\n\n## Summary\n\nThis project does great things.\n\n## Goals\n\n- Ship v1",
        });

        // Add in-progress tasks
        await invokeJsonTool(server, "update_project_doc", {
          slug: "my-project",
          doc: "tasks",
          content:
            "# Tasks\n\n## In Progress\n\n- [/] Build the API\n- [/] Write tests\n\n## Done\n\n- [x] Setup",
        });

        // Populate dependencies
        await invokeJsonTool(server, "update_project_doc", {
          slug: "my-project",
          doc: "dependencies",
          content:
            "# Dependencies — My Project\n\n## Upstream\n\n- shared-lib: Common utilities\n\n## Downstream\n\n- None yet",
        });

        // Create an active plan
        await invokeJsonTool(server, "create_project_plan", {
          slug: "my-project",
          title: "Auth System",
          summary: "JWT-based auth",
          status: "in_progress",
        });

        const result = await invokeJsonTool(server, "sync_agents_md", {
          slug: "my-project",
          codebaseAnalysis: fullAnalysis,
        });

        const text = resultText(result);

        // Verify file was written
        const agentsPath = join(wsDir, "AGENTS.md");
        expect(existsSync(agentsPath)).toBe(true);
        const fileContent = readFileSync(agentsPath, "utf-8");

        // Verify preamble
        expect(fileContent).toContain("# AGENTS.md — My Project");
        expect(fileContent).toContain("Auto-generated by cc-dag");
        expect(fileContent).toContain("## Coding Discipline");
        expect(fileContent).toContain("**DRY**");
        expect(fileContent).toContain("**Single Responsibility**");

        // Verify analysis sections
        expect(fileContent).toContain("## Tech Stack");
        expect(fileContent).toContain("TypeScript, Node.js");
        expect(fileContent).toContain("## Directory Structure");
        expect(fileContent).toContain("## File Naming Conventions");
        expect(fileContent).toContain("## Code Patterns");
        expect(fileContent).toContain("## Testing Patterns");
        expect(fileContent).toContain("Vitest, co-located test files");
        expect(fileContent).toContain("## Additional Notes");
        expect(fileContent).toContain("Uses ESM modules exclusively");

        // Verify project context sections
        expect(fileContent).toContain("## Project Overview");
        expect(fileContent).toContain("This project does great things.");
        expect(fileContent).toContain("## Current Focus");
        expect(fileContent).toContain("- [/] Build the API");
        expect(fileContent).toContain("## Dependencies");
        expect(fileContent).toContain("shared-lib: Common utilities");
        expect(fileContent).toContain("## Active Plans");
        expect(fileContent).toContain("Auth System");

        // Verify response confirms write
        expect(text).toContain("AGENTS.md written to 1 path(s)");
      } finally {
        await server.close();
      }
    });
  });

  it("omits optional analysis sections when not provided", async () => {
    await withTempDataDir(async (dataDir) => {
      const server = createTestServer();
      try {
        const wsDir = resolve(dataDir, "workspace");
        mkdirSync(wsDir, { recursive: true });

        await invokeJsonTool(server, "init_project", {
          name: "Minimal",
          description: "test",
          workspacePaths: [wsDir],
        });

        await invokeJsonTool(server, "sync_agents_md", {
          slug: "minimal",
          codebaseAnalysis: minimalAnalysis,
        });

        const fileContent = readFileSync(
          join(wsDir, "AGENTS.md"),
          "utf-8"
        );

        // Required sections present
        expect(fileContent).toContain("## Tech Stack");
        expect(fileContent).toContain("## Directory Structure");
        expect(fileContent).toContain("## File Naming Conventions");
        expect(fileContent).toContain("## Code Patterns");

        // Optional sections absent
        expect(fileContent).not.toContain("## Testing Patterns");
        expect(fileContent).not.toContain("## Additional Notes");
      } finally {
        await server.close();
      }
    });
  });

  it("omits project context sections when cc-dag docs are default template", async () => {
    await withTempDataDir(async (dataDir) => {
      const server = createTestServer();
      try {
        const wsDir = resolve(dataDir, "workspace");
        mkdirSync(wsDir, { recursive: true });

        // Don't populate any docs — leave as default template
        await invokeJsonTool(server, "init_project", {
          name: "Empty Docs",
          description: "test",
          workspacePaths: [wsDir],
        });

        await invokeJsonTool(server, "sync_agents_md", {
          slug: "empty-docs",
          codebaseAnalysis: minimalAnalysis,
        });

        const fileContent = readFileSync(
          join(wsDir, "AGENTS.md"),
          "utf-8"
        );

        // Preamble + analysis present
        expect(fileContent).toContain("# AGENTS.md — Empty Docs");
        expect(fileContent).toContain("## Tech Stack");

        // Project context sections absent (all default template)
        expect(fileContent).not.toContain("## Project Overview");
        expect(fileContent).not.toContain("## Current Focus");
        expect(fileContent).not.toContain("## Dependencies");
        expect(fileContent).not.toContain("## Active Plans");
      } finally {
        await server.close();
      }
    });
  });

  it("returns content without writing in dry run mode", async () => {
    await withTempDataDir(async (dataDir) => {
      const server = createTestServer();
      try {
        const wsDir = resolve(dataDir, "workspace");
        mkdirSync(wsDir, { recursive: true });

        await invokeJsonTool(server, "init_project", {
          name: "Dry Run",
          description: "test",
          workspacePaths: [wsDir],
        });

        const result = await invokeJsonTool(server, "sync_agents_md", {
          slug: "dry-run",
          codebaseAnalysis: minimalAnalysis,
          dryRun: true,
        });

        const text = resultText(result);

        // Content is returned
        expect(text).toContain("# AGENTS.md — Dry Run");
        expect(text).toContain("Dry run");

        // File NOT written
        expect(existsSync(join(wsDir, "AGENTS.md"))).toBe(false);
      } finally {
        await server.close();
      }
    });
  });

  it("returns error when project has no workspace paths", async () => {
    await withTempDataDir(async () => {
      const server = createTestServer();
      try {
        await invokeJsonTool(server, "init_project", {
          name: "No Paths",
          description: "test",
        });

        await expect(
          invokeJsonTool(server, "sync_agents_md", {
            slug: "no-paths",
            codebaseAnalysis: minimalAnalysis,
          })
        ).rejects.toThrow("NO_WORKSPACE_PATHS");
      } finally {
        await server.close();
      }
    });
  });

  it("warns and skips non-existent workspace paths", async () => {
    await withTempDataDir(async () => {
      const server = createTestServer();
      try {
        await invokeJsonTool(server, "init_project", {
          name: "Bad Path",
          description: "test",
          workspacePaths: ["/nonexistent/path/that/does/not/exist"],
        });

        const result = await invokeJsonTool(server, "sync_agents_md", {
          slug: "bad-path",
          codebaseAnalysis: minimalAnalysis,
        });

        const text = resultText(result);
        expect(text).toContain("Warning:");
        expect(text).toContain("/nonexistent/path/that/does/not/exist");
        expect(text).toContain("No files written");
      } finally {
        await server.close();
      }
    });
  });

  it("writes identical AGENTS.md to multiple workspace paths", async () => {
    await withTempDataDir(async (dataDir) => {
      const server = createTestServer();
      try {
        const wsDir1 = resolve(dataDir, "workspace-1");
        const wsDir2 = resolve(dataDir, "workspace-2");
        mkdirSync(wsDir1, { recursive: true });
        mkdirSync(wsDir2, { recursive: true });

        await invokeJsonTool(server, "init_project", {
          name: "Multi Path",
          description: "test",
          workspacePaths: [wsDir1, wsDir2],
        });

        await invokeJsonTool(server, "sync_agents_md", {
          slug: "multi-path",
          codebaseAnalysis: minimalAnalysis,
        });

        const content1 = readFileSync(join(wsDir1, "AGENTS.md"), "utf-8");
        const content2 = readFileSync(join(wsDir2, "AGENTS.md"), "utf-8");

        expect(content1).toBe(content2);
        expect(content1).toContain("# AGENTS.md — Multi Path");
      } finally {
        await server.close();
      }
    });
  });

  it("downgrades dependency headers and omits default template deps", async () => {
    await withTempDataDir(async (dataDir) => {
      const server = createTestServer();
      try {
        const wsDir = resolve(dataDir, "workspace");
        mkdirSync(wsDir, { recursive: true });

        // Project with default deps (should have no Dependencies section)
        await invokeJsonTool(server, "init_project", {
          name: "Default Deps",
          description: "test",
          workspacePaths: [wsDir],
        });

        await invokeJsonTool(server, "sync_agents_md", {
          slug: "default-deps",
          codebaseAnalysis: minimalAnalysis,
        });

        let fileContent = readFileSync(join(wsDir, "AGENTS.md"), "utf-8");
        expect(fileContent).not.toContain("## Dependencies");

        // Now populate dependencies
        await invokeJsonTool(server, "update_project_doc", {
          slug: "default-deps",
          doc: "dependencies",
          content:
            "# Dependencies — Default Deps\n\n## Upstream\n\n- auth-service: Authentication provider\n\n## Downstream\n\n- None yet",
        });

        await invokeJsonTool(server, "sync_agents_md", {
          slug: "default-deps",
          codebaseAnalysis: minimalAnalysis,
        });

        fileContent = readFileSync(join(wsDir, "AGENTS.md"), "utf-8");
        expect(fileContent).toContain("## Dependencies");
        // Headers should be downgraded to ### when embedded under ## Dependencies
        expect(fileContent).toContain("### Upstream");
        expect(fileContent).toContain("auth-service: Authentication provider");
      } finally {
        await server.close();
      }
    });
  });
});
