import { z } from "zod";
import {
  readFileSync,
  writeFileSync,
  existsSync,
  symlinkSync,
  unlinkSync,
  lstatSync,
} from "node:fs";
import { resolve, join } from "node:path";
import { getDataDir } from "../utils/paths.js";
import { readRootMeta } from "../utils/dag.js";
import { readPlanIndex } from "../utils/project-memory.js";
import {
  extractOverviewContent,
  extractInProgressTasks,
  extractDependenciesContent,
} from "../utils/content-assembly.js";
import {
  projectNotFound,
  noWorkspacePaths,
  formatError,
} from "../utils/errors.js";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

// ---------------------------------------------------------------------------
// Static preamble
// ---------------------------------------------------------------------------

function buildPreamble(name: string, slug: string): string {
  return `# AGENTS.md — ${name}

> Auto-generated by SPOC. Do not edit manually.
> Regenerate: \`sync_agents_md\` (slug: ${slug})

---

## Coding Discipline

You are working in an existing codebase maintained by a team.
Your code must be indistinguishable from the team's existing code.

### Principles (Non-Negotiable)

- **DRY**: Never duplicate logic. If it exists, reuse it. If it almost exists, extend it.
- **Single Responsibility**: Each file, function, and class does one thing.
- **Open/Closed**: Extend behavior without modifying existing working code.
- **Dependency Inversion**: Depend on abstractions, not concrete implementations.
- **Interface Segregation**: Keep interfaces focused and minimal.
- **Consistency Over Cleverness**: Match the team's conventions even if a "better" approach exists.
- **No Redundant Abstractions**: If a similar pattern exists, use it. Do not create parallel ones.`;
}

// ---------------------------------------------------------------------------
// Codebase analysis assembly
// ---------------------------------------------------------------------------

interface CodebaseAnalysis {
  techStack: string;
  directoryStructure: string;
  fileNaming: string;
  codePatterns: string;
  testingPatterns?: string;
  additionalNotes?: string;
}

function buildAnalysisSections(analysis: CodebaseAnalysis): string {
  const sections: string[] = [];

  sections.push(`\n## Tech Stack\n\n${analysis.techStack}`);
  sections.push(`\n## Directory Structure\n\n${analysis.directoryStructure}`);
  sections.push(`\n## File Naming Conventions\n\n${analysis.fileNaming}`);
  sections.push(`\n## Code Patterns\n\n${analysis.codePatterns}`);

  if (analysis.testingPatterns?.trim()) {
    sections.push(`\n## Testing Patterns\n\n${analysis.testingPatterns}`);
  }
  if (analysis.additionalNotes?.trim()) {
    sections.push(`\n## Additional Notes\n\n${analysis.additionalNotes}`);
  }

  return sections.join("\n");
}

// ---------------------------------------------------------------------------
// Project context assembly
// ---------------------------------------------------------------------------

function buildProjectContext(projectDir: string): string {
  const sections: string[] = [];

  // Overview
  const overviewPath = resolve(projectDir, "overview.md");
  if (existsSync(overviewPath)) {
    const overviewRaw = readFileSync(overviewPath, "utf-8");
    const overviewContent = extractOverviewContent(overviewRaw);
    if (overviewContent) {
      sections.push(`\n## Project Overview\n\n${overviewContent}`);
    }
  }

  // Current Focus (in-progress tasks)
  const tasksPath = resolve(projectDir, "tasks.md");
  if (existsSync(tasksPath)) {
    const tasksRaw = readFileSync(tasksPath, "utf-8");
    const inProgress = extractInProgressTasks(tasksRaw);
    if (inProgress.length > 0) {
      sections.push(`\n## Current Focus\n\n${inProgress.join("\n")}`);
    }
  }

  // Dependencies
  const depsPath = resolve(projectDir, "dependencies.md");
  if (existsSync(depsPath)) {
    const depsRaw = readFileSync(depsPath, "utf-8");
    const depsContent = extractDependenciesContent(depsRaw);
    if (depsContent) {
      sections.push(`\n## Dependencies\n\n${depsContent}`);
    }
  }

  // Active Plans
  const planIndex = readPlanIndex(projectDir);
  const activePlans = planIndex.plans.filter(
    (p) => p.status === "in_progress" || p.status === "planned"
  );
  if (activePlans.length > 0) {
    const bullets = activePlans
      .map((p) => {
        const summary = p.summary ? `: ${p.summary}` : "";
        return `- **${p.title}** (${p.status})${summary}`;
      })
      .join("\n");
    sections.push(`\n## Active Plans\n\n${bullets}`);
  }

  return sections.join("\n");
}

// ---------------------------------------------------------------------------
// Tool registration
// ---------------------------------------------------------------------------

export function registerSyncAgentsMd(server: McpServer) {
  server.tool(
    "sync_agents_md",
    "Generate and write an AGENTS.md file to a project's workspace directories. Assembles coding discipline rules, LLM-provided codebase analysis, and SPOC project context into a single guardrail document. The caller should analyze the project codebase first and provide findings via codebaseAnalysis.",
    {
      slug: z.string().describe("Project slug"),
      codebaseAnalysis: z
        .object({
          directoryStructure: z
            .string()
            .describe("How the project organizes directories/modules"),
          fileNaming: z
            .string()
            .describe("File naming conventions observed"),
          codePatterns: z.string().describe("Recurring code patterns"),
          techStack: z
            .string()
            .describe("Languages, frameworks, key dependencies"),
          testingPatterns: z
            .string()
            .optional()
            .describe("How tests are organized and written"),
          additionalNotes: z
            .string()
            .optional()
            .describe("Anything else relevant"),
        })
        .describe("LLM-provided analysis of the project codebase"),
      dryRun: z
        .boolean()
        .optional()
        .default(false)
        .describe("Return generated content without writing to disk"),
    },
    async (params) => {
      try {
        const dataDir = getDataDir();
        const rootMeta = readRootMeta(dataDir);

        // Verify project exists
        const projectNode = rootMeta.projects.find(
          (p) => p.id === params.slug
        );
        if (!projectNode) {
          return formatError(projectNotFound(params.slug));
        }

        // Read project meta
        const projectDir = resolve(dataDir, "projects", params.slug);
        const metaPath = resolve(projectDir, "meta.json");
        const meta = JSON.parse(readFileSync(metaPath, "utf-8")) as Record<
          string,
          unknown
        >;

        const name = (meta.name as string) ?? params.slug;
        const workspacePaths = Array.isArray(meta.workspacePaths)
          ? (meta.workspacePaths as string[])
          : [];

        if (workspacePaths.length === 0) {
          return formatError(noWorkspacePaths(params.slug));
        }

        // Assemble AGENTS.md content
        const parts: string[] = [];
        parts.push(buildPreamble(name, params.slug));
        parts.push("\n\n---");
        parts.push(buildAnalysisSections(params.codebaseAnalysis));

        const projectContext = buildProjectContext(projectDir);
        if (projectContext) {
          parts.push("\n\n---");
          parts.push(projectContext);
        }

        const content = parts.join("") + "\n";

        // Write source file to SPOC data dir and create symlinks
        const sourcePath = resolve(projectDir, "AGENTS.md");
        const warnings: string[] = [];
        const symlinked: string[] = [];

        if (!params.dryRun) {
          // Write source of truth to SPOC data dir
          writeFileSync(sourcePath, content, "utf-8");

          // Create symlinks from each workspace path
          for (const wsPath of workspacePaths) {
            if (!existsSync(wsPath)) {
              warnings.push(
                `Warning: workspace path "${wsPath}" does not exist, skipped.`
              );
              continue;
            }

            const linkPath = join(wsPath, "AGENTS.md");

            // Remove existing file or symlink at the target
            try {
              lstatSync(linkPath);
              unlinkSync(linkPath);
            } catch {
              // Does not exist — nothing to remove
            }

            symlinkSync(sourcePath, linkPath);
            symlinked.push(linkPath);
          }
        }

        // Build response
        const responseParts: string[] = [];

        if (params.dryRun) {
          responseParts.push("**Dry run** — content generated but not written.\n");
        } else if (symlinked.length > 0) {
          responseParts.push(
            `✅ AGENTS.md written to \`${sourcePath}\`\nsymlink created at ${symlinked.length} path(s):\n${symlinked.map((p) => `- ${p}`).join("\n")}\n`
          );
        } else {
          responseParts.push(
            `⚠️ AGENTS.md written to \`${sourcePath}\` but no symlinks created — all workspace paths are non-existent.\n`
          );
        }

        if (warnings.length > 0) {
          responseParts.push(warnings.join("\n") + "\n");
        }

        responseParts.push("\n---\n\n" + content);

        return {
          content: [
            {
              type: "text" as const,
              text: responseParts.join("\n"),
            },
          ],
        };
      } catch (err) {
        return {
          content: [
            {
              type: "text" as const,
              text: `Error: ${err instanceof Error ? err.message : String(err)}`,
            },
          ],
          isError: true,
        };
      }
    }
  );
}
